= Arsalan Cheema  - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ClinicIO

---

== Overview
// command line constraint
// 2 paragraphs
// number sections
// pdf
This page showcases my contributions to a software engineering group project as part of a university module. We built a
desktop application named ClinicIO. ClinicIO is intended for medical clinic receptionists and doctors. It allows our
target users to manage a multitude of clinic processes such as storing patient records and managing queues. While there
is a Graphical User Inteface (GUI) for displaying results, a key constraint for the module was to ensure that the
application is used through a text interface. The program logic is written in Java and the GUI is written in JavaFX.

== Summary of contributions

* *Major enhancement*:
added *the ability to access detailed statistics and visualizations*
** What it does: allows the user to track the activity of a clinic through objective metrics, in a simple manner.
** Justification: This feature improves the product significantly because it provides a user with insight to make
decisions regarding the clinic's processes and improve efficiency.
** Highlights: This enhancement spans across the major functions of a clinic. It was a challenge to design and implement
a flexible yet powerful interface through which different types of visualizations can be easily created. This was done
in order to ensure that many more metrics can be programmed to be tracked in the future.

* *Minor enhancement*: added commands to export various types of patient data to a human editable format (CSV).

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:

** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** Reviewed team mates' code contributions (with non-trivial review comments):
**** https://github.com/CS2103-AY1819S1-W14-1/main/pull/60[#60],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/132[#132],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/140[#140],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/144[#144],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/152[#152],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/179[#179],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/238[#238]

*** Reported bugs and suggestions for other teams in the cohort:
**** https://github.com/CS2103-AY1819S1-W13-2/main/issues/148[1],
https://github.com/CS2103-AY1819S1-W13-2/main/issues/157[2],
https://github.com/CS2103-AY1819S1-W13-2/main/issues/163[3],
https://github.com/CS2103-AY1819S1-W13-2/main/issues/167[4],
https://github.com/CS2103-AY1819S1-W13-2/main/issues/170[5]

*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])

== Contributions to the User Guide

|===
|_The following are sections I contributed to the User Guide. They showcase my ability to write documentation targeting
end-users
._
|===

include::../UserGuide.adoc[tag=datacommands]

== Contributions to the Developer Guide

|===
|_The following below are sections I contributed to the Developer Guide. They showcase my ability to write technical
documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=export]

include::../DeveloperGuide.adoc[tag=analytics]

